user_name = input("Enter  your name: ")
print('Hi ' + user_name + ' !')
age = input('Enter your age: ')
print("You are " + age + " years old.")
n1 = input("Enter number 1: ")
n2 = input("Enter number 2: ")
#sum = int(n1) + int(n2)
sum = float(n1) + float(n2)
print("The sum of " + str(n1) + " and " + str(n2) + " is " + str(sum) + ".")
#print("The sum of " + str(n1) + " and " + str(n2) + " is " + str(int(n1)+int(n2)) + ".")
